import sqlite3
con = sqlite3.connect('db2.db')
c = con.cursor()

#c.execute('create table student (regno text primary key,name text,collname text)')
c.execute("insert into student values ('001','soujanya','rnsit')")
c.execute("insert into student values ('002','souj','ewit')")
c.execute("insert into student values ('003','janya','bms')")
c.execute("insert into student values ('004','gowda','kvs')")
con.commit()
c.execute('select name from student')
data = c.fetchall()
print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[3])
c.close()
con.close()
